services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true

    test.App\Repository\CategoryRepository: '@App\Repository\CategoryRepository'
    test.App\Repository\CircaDateRepository: '@App\Repository\CircaDateRepository'
    test.App\Repository\CivilizationRepository: '@App\Repository\CivilizationRepository'
    test.App\Repository\ImageRepository: '@App\Repository\ImageRepository'
    test.App\Repository\InscriptionStyleRepository: '@App\Repository\InscriptionStyleRepository'
    test.App\Repository\ItemRepository: '@App\Repository\ItemRepository'
    test.App\Repository\LocationRepository: '@App\Repository\LocationRepository'
    test.App\Repository\MaterialRepository: '@App\Repository\MaterialRepository'
    test.App\Repository\RemoteImageRepository: '@App\Repository\RemoteImageRepository'
    test.App\Repository\SubjectRepository: '@App\Repository\SubjectRepository'
    test.App\Repository\TechniqueRepository: '@App\Repository\TechniqueRepository'
